#maven plugin help mojo generation informations
#Fri Jun 05 15:14:11 IST 2026
destinationDirectory=C\:\\Users\\yogesh.potdar\\eclipse-workspace\\Playwright_Project\\target\\generated-sources\\plugin
helpPackageName=Playwright_Project.Playwright_Project
